name: CI

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        destination: [dev]

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Initializing AWS
        run: |
          mkdir -p ~/.aws
          touch ~/.aws/credentials
          [ -z ${SERVICE_NAME} ] && export SERVICE_NAME=${DEFAULT_SERVICE_NAME}
          echo "[${SERVICE_NAME}-${{ matrix.destination }}]" >> ~/.aws/credentials
          echo "aws_access_key_id=${AWS_ACCESS_KEY_ID}" >> ~/.aws/credentials
          echo -n "aws_secret_access_key=${AWS_SECRET_ACCESS_KEY}" >> ~/.aws/credentials
        env:
          DEFAULT_SERVICE_NAME: ${{ secrets.DEFAULT_SERVICE_NAME }}
          SERVICE_NAME: ${{ secrets.SERVICE_NAME }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Deploy to ${{ matrix.destination }}
        run: echo "Will deploy to ${{ matrix.destination }}"

      - name: NPM Install
        run: npm ci

      - name: Deploy Server
        run: |
          npx serverless deploy
        env:
          SECRETS_PASSWORD: ${{ secrets.SECRETS_PASSWORD_DEV }}

      - name: Update web view version with HTTP call
        run: |
          curl -X POST https://jlm0lhpfob.execute-api.us-east-1.amazonaws.com/dev/transfer \
            -H 'Content-Type: application/json' \
            -H "web-view-token: ${{ secrets.AUTH_TOKEN }}"